add libXrandr library
From glfw v2.6, it adds Xrandr code path, so in order to compile Linux
successfully, we need to add this library.

Otherwise, there are following errors:

    ../../../lib/linux/Debug/libcocos2d.so: undefined reference to `XRRSetScreenConfig'
    ../../../lib/linux/Debug/libcocos2d.so: undefined reference to `XRRConfigCurrentConfiguration'
    ../../../lib/linux/Debug/libcocos2d.so: undefined reference to `XRRSelectInput'
    ../../../lib/linux/Debug/libcocos2d.so: undefined reference to `XRRFreeScreenConfigInfo'
    ../../../lib/linux/Debug/libcocos2d.so: undefined reference to `XRRConfigCurrentRate'
    ../../../lib/linux/Debug/libcocos2d.so: undefined reference to `XRRConfigRates'
    ../../../lib/linux/Debug/libcocos2d.so: undefined reference to `XRRQueryExtension'
    ../../../lib/linux/Debug/libcocos2d.so: undefined reference to `XRRGetScreenInfo'
    ../../../lib/linux/Debug/libcocos2d.so: undefined reference to `XRRUpdateConfiguration'
    ../../../lib/linux/Debug/libcocos2d.so: undefined reference to `XRRSetScreenConfigAndRate'
    ../../../lib/linux/Debug/libcocos2d.so: undefined reference to `XRRConfigSizes'
    collect2: ld returned 1 exit status
    make: *** [TestCpp] Error 1